# Softmax Classfication


## Cross-entropy cost function

* 예측한 값이 오답에 가까울 수록 cost를 크게 가중시키고 정답에 가까울 수록 0에 가깝게 해주는 function
* D(S, L) = -sigma(L * log(S))
* logistic cost function과 결과적으로 같다

In [4]:
import tensorflow as tf

In [19]:
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5],
         [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0],
          [1, 0, 0], [1, 0 ,0]] # one hot encoding

X = tf.placeholder(tf.float32, shape = [None, 4])
Y = tf.placeholder(tf.float32, shape = [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name= 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b) #logit ; probability 표현

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(optimizer, feed_dict={X:x_data,Y:y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X:x_data,Y:y_data}))
    a = sess.run(hypothesis, feed_dict={X:[[1,11,7,9],
                                          [1, 3, 4, 3],
                                          [1, 1, 0, 1]]})
    print(a, sess.run(tf.arg_max(a,1))) # how to descript labels

0 3.318849
200 0.6475714
400 0.53041035
600 0.4482196
800 0.37700516
1000 0.30752718
1200 0.24102384
1400 0.21693446
1600 0.19813934
1800 0.18220699
2000 0.16854516
[[1.21582951e-02 9.87831056e-01 1.06146135e-05]
 [8.03162396e-01 1.79770574e-01 1.70670059e-02]
 [3.13764019e-08 4.39967000e-04 9.99559939e-01]] [1 0 2]


RuntimeError: Attempted to use a closed Session.